# Generated by Django 4.2.1 on 2023-05-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=500)),
                ('occupation', models.CharField(max_length=500)),
                ('dob', models.DateField(default='None')),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=2000)),
                ('education', models.CharField(max_length=200)),
                ('work_experience', models.TextField(max_length=1000)),
                ('skills', models.TextField(max_length=1000)),
                ('hobbies', models.TextField(max_length=1000)),
            ],
        ),
    ]
